//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioinformaticsSuite.Module.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BioinformaticsSuite.Module.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AatI agg|cct
        ///AatII gacgt|c
        ///Acc16I tgc|gca
        ///AccII cg|cg
        ///AccIII t|ccgga
        ///AclI aa|cgtt
        ///AcvI cac|gtg
        ///AfaI gt|ac
        ///AfeI agc|gct
        ///AflII c|ttaag
        ///AgeI a|ccggt
        ///AhlI a|ctagt
        ///Alw441 g|tgcac
        ///AluI ag|ct
        ///Aor51HI agc|gct
        ///ApaI gggcc|c
        ///ApaLI g|tgcac
        ///AscI gg|cgcgcc
        ///AseI at|taat
        ///Asp718I g|gtacc
        ///AsuII tt|cgaa
        ///AvaI c|ycgrg
        ///AviII tgc|gca
        ///AvrII c|ctagg
        ///BalI tgg|cca
        ///BamHI g|gatcc
        ///BanIII at|cgat
        ///BbeI ggcgc|c
        ///BbrPI cac|gtg
        ///BbuI gcatg|c
        ///BcuI a|ctagt
        ///BclI t|gatca
        ///BfaI c|tag
        ///BfrI c|ttaag
        ///BfrBI atg|cat
        ///BglI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Enzymes {
            get {
                return ResourceManager.GetString("Enzymes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;SequenceLabel
        ///TGTAATTGGTAAGGTGGTAACCACTGACCGTTACTAACGCCCAACTATAAAGTTTAGAGG
        ///TTACTTGGGGTTCGTCCATGAATGAGCACGCGTACGTATAAATGCCATATACCGGTGAAA
        ///AGTCTTGTCACCTAGTGACGTCGAGAGACTGCATCAACTTGTGTTACCTTAAACCGCTGC
        ///GAATAGGTCCTTTAGGTTATATGCTTCACGACTGAGTCCGCCTCCATAGAGACCTTCGTC
        ///CTGTTCAACATCAACGTGTCCGGGATGTGGTGGGACCTTAACATTCTGTGAGGATTGCCA
        ///CGGGGCACCCTTCCCXCTTTATACGATGTATTATGGTTCTTTACCGGTTTGAACCACGGC
        ///ATTGATGATCAGAACAGTGCTGATTGTGCACATCGAAAAGCACGGCCTCTATGTCCGCGT
        ///CCTCCCGCCTGACGACGTGTATGGGATACGCTCGGCACTTTTAACTGTGAATTCCATTCT
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InvalidLabelledSequence {
            get {
                return ResourceManager.GetString("InvalidLabelledSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;Sequence1
        ///ATGCTTAGTGGACTAAGAGGCGCGGGCGGCCGGTATTAGGTATCACCCGCCCTCCACAAT
        ///CCGCGTGCGGGCATCTCGATTCTTTTTTCTGAACTCTGTCCTTCGATGTCTTGGAAAATA
        ///ACATAATTTCTTGCATGTTGTTCGTACCCCAGGACGGGAGCGCGTAACCGTCAATACGTG
        ///TCGATCGTAACACTTCTGTATATGGGCTAAGCCATAGTGGGCGTGTCTGGTATCTCCAAG
        ///TGCCTACGCCGTCAGACAAGAGACTGAGTCCCCTACTGCCGAACGGCATGGTTGCCTTCC
        ///CCGTTCATATATGATATAACGGGTTTCCAGTACTTAACGCAAACCTATATATAAATCCCC
        ///AGAGGCGTGTTCAAGGGCTTTAGACAGTGGGATCGATCCGTTCGATTAGTGCAGGGAAAA
        ///AAACAATCCTTACGGGAGACGATGAATCGGTGGGAGACTACACCTCTGGAACCTTAATTA
        ///TATG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultipleLabelledSequences {
            get {
                return ResourceManager.GetString("MultipleLabelledSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;SequenceLabel
        ///TGTAATTGGTAAGGTGGTAACCACTGACCGTTACTAACGCCCAACTATAAAGTTTAGAGG
        ///TTACTTGGGGTTCGTCCATGAATGAGCACGCGTACGTATAAATGCCATATACCGGTGAAA
        ///AGTCTTGTCACCTAGTGACGTCGAGAGACTGCATCAACTTGTGTTACCTTAAACCGCTGC
        ///GAATAGGTCCTTTAGGTTATATGCTTCACGACTGAGTCCGCCTCCATAGAGACCTTCGTC
        ///CTGTTCAACATCAACGTGTCCGGGATGTGGTGGGACCTTAACATTCTGTGAGGATTGCCA
        ///CGGGGCACCCTTCCCGCTTTATACGATGTATTATGGTTCTTTACCGGTTTGAACCACGGC
        ///ATTGATGATCAGAACAGTGCTGATTGTGCACATCGAAAAGCACGGCCTCTATGTCCGCGT
        ///CCTCCCGCCTGACGACGTGTATGGGATACGCTCGGCACTTTTAACTGTGAATTCCATTCT
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingleLabelledSequence {
            get {
                return ResourceManager.GetString("SingleLabelledSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTAACCCCCTTAGTTCACGGGGTTACTTAAAGGAAGTTATCACGGGGAATCCCACATTGA
        ///TCTGGCTGGGTCCAACGTTATAATTGGACGACTTTATGCGGCTCGACTGCCAAAGGTGGG
        ///CGGGGTCAGATAAGGACAGATGGGGAATGTTCTCTCCCTACTTGTGTATGAATGCGATGA
        ///TCTGGACGGACACCAGCACACTCTACACGGAGTAAGTCTAACAGATCAGATTGGATGTTC
        ///AGAAGGACGTCATGCCGTCGGGATTCCCGAGTTGCGGATATGTCAGAGCACACTATCGGA
        ///CCGTCGCAGAGGATGTCCAGCAAAAACATCTTACATATTGCTATCCGAAGGACGTCCGGG
        ///GACGTTGGCAAACCACAACCGGGGTTTTAGTCTGCACCTGCAAGTTTTGTGTAACTTTCG
        ///TGCCTGCACCTCTCCGGGGAGAAAGGTATATCAGCCCTCACTAAAGACGAACCCTATATT
        ///CACCCTGTCGTACCGG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnlabelledSequence {
            get {
                return ResourceManager.GetString("UnlabelledSequence", resourceCulture);
            }
        }
    }
}
